# Generated by Django 5.0.6 on 2024-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='', max_length=10),
        ),
    ]
