# Generated by Django 5.0.6 on 2024-07-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
